### ISSUE TITLE
JS스크립트 도메인 변경 부탁드립니다.

### ISSUE THREAD

**Issue by daumPostcode** [bernard-kms/react-daum-postcode#16]
안녕하세요~
다음우편번호서비스 담당자입니다.

저희 서비스를 React모듈로 만들어 배포해 주셔서 진심으로 감사드립니다. ^^
다름이 아니라, 현재 저희 공식가이드페이지 (http://postcode.map.daum.net/guide) 에서도 정의하고 있듯이

API 스크립트의 주소가 변경되었습니다.
```
https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js
```

위 URL로 변경되었으며, 
해당 버전은 현재 이용하고 계시는 ssl.daumcdn.net에 연결된 버전과 다르게, loader-core가 통합된 버전이라, 위 파일 하나만 다운받으면 저희 서비스를 이용가능합니다.

추가로 지속적인 서비스 유지보수는 위 도메인이 메인이며, 확정이 되진 않았으나, ssl.daumcdn.net도메인에 연결된 버전은 종료할 계획을 가지고 있기 때문에, t1.daumcdn.net으로 변경을 해주시면 좋을 것 같습니다.

감사합니다.

**Comment by bernard-kms** [comment]
안녕하세요! 놓치고 있던 소식이라, 직접 알려주셔서 무척 감사합니다.
말씀해주신 대로 변경된 스크립트로 수정하고, 새로운 메이저 버전으로 릴리즈하도록 하겠습니다.
좋은 서비스 운영해주심에 다시한번 감사드립니다 :)

**Comment by bernard-kms** [comment]
`v2.0.0`으로 배포되었습니다.

**Comment by daumPostcode** [comment]
@bernard-kms 
빠른 수정 감사드립니다 ^^ 코로나 조심하시고 즐거운 하루 보내세요~
