### ISSUE TITLE
onSearch 관련 오류

### ISSUE THREAD

**Issue by lshwa80** [bernard-kms/react-daum-postcode#17]
라이브러리 잘 사용하고 있습니다.
최신버전으로 업데이트해서 사용하고 있는데, 아래 내용의 오류가 발생하고 있습니다.
확인 한 번 부탁드리겠습니다.

https://github.com/daumPostcode/QnA/issues/653

**Comment by bernard-kms** [comment]
안녕하세요! 이슈를 제보해주셔서 감사합니다.
3748a2906f62d7e1890bd4cb42139a3f19e7f6f3 에서 해당 문제를 고치고, `v2.0.1`로 배포되었습니다.
