### ISSUE TITLE
ionic-react 환경 Cannot read property 'document' of null 오류

### ISSUE THREAD

**Issue by KimGnab** [bernard-kms/react-daum-postcode#30]
ionic-react 환경에서 사용시 Home.tsx에서는 정상적으로 표시되는데
모달창에서 사용시 간헐적으로 작동이 되다가

postcode.v2.js:1 Uncaught TypeError: Cannot read property 'document' of null
<img width="881" alt="스크린샷 2021-03-27 오후 7 59 06" src="https://user-images.githubusercontent.com/49812837/112718522-e51fbb00-8f36-11eb-8e03-e2e2ba8b94c6.png">

위와같은 오류와 함께 작동하지 않습니다.
컴포넌트 내부의 iframe src가 about:blank로 표시됩니다.
예제링크
 [https://codesandbox.io/s/cold-night-wgs7p](https://codesandbox.io/s/cold-night-wgs7p)

[다음QnA](https://github.com/daumPostcode/QnA/issues/650#issue-697433304)
위 상황과 비슷한 사항인것같습니다.

**Comment by Normaltic** [comment]
안녕하세요! 

`react-daum-postcode` 컴포넌트는 `componentDidMount` 시점에, 내부 `div` 태그에 다음 우편번호 서비스 초기화를 진행합니다.  f가 `null` 이면 `b.contentWindow`가 현재 돔에 없다는 말인데, `ionic-react` 를 잘 모르지만, `ionic-react` 와 `react` 의 lifecycle이 작동하는 타이밍이 달라 발생하는 이슈 같습니다.

```jsx
import React from "react";

class Test extends React.Component {
  componentDidMount() {
    console.log("Test did mount");
    const t = document.getElementById("test");
    t.innerText = "123";
  }

  render() {
    return <div id="test">test</div>;
  }
}

export default Test;
```

위 컴포넌트는 리액트에서 정상적으로 작동하나, 올려주신 샌드박스의 `IonModal` 안에 넣고 실행시키면 정상작동 되지 않습니다.

![image](https://user-images.githubusercontent.com/24601577/113144251-013d9800-9268-11eb-9171-41e42baae94b.png)

또, `IonModal` 컴포넌트에 `onDidPresent={() => console.log("Modal did present")}` 를 할당하면, `"Test did mount"` 가 먼저 출력됩니다.

![image](https://user-images.githubusercontent.com/24601577/113144501-42ce4300-9268-11eb-9125-2258d460cf84.png)

이를 보아, `ionic-react`가 컴포넌트를 돔에 반영하기 전에, 컴포넌트의 `componentDidMount` 함수가 호출이 되고, 아직 돔에 반영되지 않아 해당 값이 `null` 이어서 오류가 발생한다고 생각합니다. ( 실제로, 개발자도구를 열어둔 상태에서 진행하면, 모달이 열리기 전에 오류가 발생합니다. )

`IonModal`의 `onDidPresent` 함수를 이용하거나, 별도의 Wrapper Component 를 통하여 lifecycle 함수 호출 시점을 맞추는 방향으로, 해당 오류를 회피할 수 있을것으로 보입니다.

**Comment by KimGnab** [comment]
> 안녕하세요!
> 
> `react-daum-postcode` 컴포넌트는 `componentDidMount` 시점에, 내부 `div` 태그에 다음 우편번호 서비스 초기화를 진행합니다. f가 `null` 이면 `b.contentWindow`가 현재 돔에 없다는 말인데, `ionic-react` 를 잘 모르지만, `ionic-react` 와 `react` 의 lifecycle이 작동하는 타이밍이 달라 발생하는 이슈 같습니다.
> 
> ```js
> import React from "react";
> 
> class Test extends React.Component {
>   componentDidMount() {
>     console.log("Test did mount");
>     const t = document.getElementById("test");
>     t.innerText = "123";
>   }
> 
>   render() {
>     return <div id="test">test</div>;
>   }
> }
> 
> export default Test;
> ```
> 
> 위 컴포넌트는 리액트에서 정상적으로 작동하나, 올려주신 샌드박스의 `IonModal` 안에 넣고 실행시키면 정상작동 되지 않습니다.
> 
> ![image](https://user-images.githubusercontent.com/24601577/113144251-013d9800-9268-11eb-9171-41e42baae94b.png)
> 
> 또, `IonModal` 컴포넌트에 `onDidPresent={() => console.log("Modal did present")}` 를 할당하면, `"Test did mount"` 가 먼저 출력됩니다.
> 
> ![image](https://user-images.githubusercontent.com/24601577/113144501-42ce4300-9268-11eb-9125-2258d460cf84.png)
> 
> 이를 보아, `ionic-react`가 컴포넌트를 돔에 반영하기 전에, 컴포넌트의 `componentDidMount` 함수가 호출이 되고, 아직 돔에 반영되지 않아 해당 값이 `null` 이어서 오류가 발생한다고 생각합니다. ( 실제로, 개발자도구를 열어둔 상태에서 진행하면, 모달이 열리기 전에 오류가 발생합니다. )
> 
> 확실한 해결방법은 말씀드리기 힘드나, `IonModal`의 `onDidPresent` 함수를 이용하거나, 별도의 Wrapper Component 를 통하여 lifecycle 함수 호출 시점을 맞추는 방향으로, 해당 오류를 회피할 수 있을것으로 보입니다.

안녕하세요 onDidPresent 함수를 활용해 모달이 열린후에 컴포넌트를 표시하도록 처리해 오류를 해결했습니다.
부족한 내용으로 문의드렸는데 깔끔한 답변 감사합니다!!
