### ISSUE TITLE
시군구 영어가 AddressData type에서 빠져서 이 부분 type에 추가가 필요해보입니다. 

### ISSUE THREAD

**Issue by Wonjuny0804** [bernard-kms/react-daum-postcode#39]
type AddressData에
넘어오는 sigunguEnglish등 영어로 된 정보들에 대한 인터페이스가 빠졌습니다.
추가가 필요해보입니다. 
- sigunguEnglish
- bnameEnglish

**Comment by Normaltic** [comment]
안녕하세요! 이슈 감사드립니다.

최근 라이브러리를 `3.0.0` 으로 릴리즈 하며, `sigunguEnglish`, `bnameEnglish` 등 누락된 부분들이 추가되었습니다.
해당 명세가 필요하실 경우 업데이트 후 사용해주시면 될 것 같습니다.
업데이트 시, 타입 이름이 `type AddressData` 에서 `interface Address` 로 변경되었으니 참고 부탁드립니다.

https://github.com/bernard-kms/react-daum-postcode/blob/e2fac655caf6c17d031554448555b696aeab71ff/src/loadPostcode.ts#L45

**Comment by Wonjuny0804** [comment]
감사합니다!!
