### ISSUE TITLE
interface Address가 any 타입으로 인식

### ISSUE THREAD

**Issue by kim-youngseok-bm** [bernard-kms/react-daum-postcode#41]
안녕하세요 버전 3으로 넘어가면서 interface AddressData가 Address 이름으로 바뀌어

import DaumPostcode, { Address } from 'react-daum-postcode'; 식으로 import 변경 후

Address가 any 타입으로 인식이 되네요.

index.d.ts를 보니 
import DaumPostcode, { DaumPostcodeProps } from './DaumPostcode';
import { Address, Search, State } from 'loadPostcode';

이런 식으로 DaumPostcode만 상대경로로 설정을 해 놓으셨던데 혹시 이유가 뭔지 궁금해서 문의드립니다.

제 vscode 설정이 잘못되어 인식을 못 하는 걸로 판단해서 임의로 loadPostcode도 './loadPostcode'로 변경 후 사용 중입니다.

**Comment by Normaltic** [comment]
안녕하세요, 이슈 감사합니다!

이런.. 특별한 이유가 있는게 아니라, 수정 중에 실수가 있었던것 같습니다. `loadPostcode` 도 상대 경로로 들고와야 합니다. 수정이 필요하네요..

지금은 코드를 직접 수정하지 않더라도, `import { Address } from 'react-daum-postcode/lib/loadPostcode` 를 통해 타입을 가져올 수 있을것 같습니다!

**Comment by Normaltic** [comment]
안녕하세요!

[3.0.1](https://github.com/bernard-kms/react-daum-postcode/releases/tag/v3.0.1) 에서, 해당 문제를 수정하였고, 배포 완료되었습니다.
