### ISSUE TITLE
502 코드 예외처리 관련

### ISSUE THREAD

**Issue by bananike** [bernard-kms/react-daum-postcode#43]
502 에러의 경우 어떻게 예외처리(안내 메세지 등 다른 컴포넌트 렌더링)를 할수 있는지 문의드립니다.

**Comment by Normaltic** [comment]
안녕하세요! `react-daum-postcode` 는 다음 우편번호 서비스를 리액트에서 간단하게 사용할 수 있도록 만든 라이브러리 입니다.

현재 라이브러리에서 제공하는 예외처리는 "우편번호 서비스 스크립트 로드에 실패했을 때" 이며, 이는 `errorMessage` 로 다른 컴포넌트를 전달하여 랜더링할 수 있습니다. 그 외에, 우편번호 검색 도중 발생하는 에러는 다음 우편번호 서비스에 문의해 주세요.

**Comment by Normaltic** [comment]
duplicated https://github.com/daumPostcode/QnA/issues/880
