### ISSUE TITLE
DaumPostcode를 렌더링 하면 오류가 뜹니다

### ISSUE THREAD

**Issue by Unknown123465** [bernard-kms/react-daum-postcode#45]
처음 렌더링 하면
Uncaught TypeError: Cannot read properties of undefined (reading 'postcode')
The above error occurred in the <b> component:
이 오류가 뜨면서 DaumPostcode 컴포넌트를 제외한 나머지 컴포넌트가 사라집니다.
코드 수정해서 컴파일시키면 사라진 컴포넌트가 다시 생기는데 
최신버전으로 바꿔도 오류나고 그렇다고 낮은 버전으로 해도 오류가 생깁니다.
Model컴포넌트 적용해도 마찬가지고
{state && <DaumPostcode />} <- 이렇게 해도 오류가 뜹니다.

어떻게 해야 해결 되나요?

**Comment by Normaltic** [comment]
안녕하세요! 저희는 Model 이라는 컴포넌트가 존재하지 않고, 어느 환경에서 어떻게 적용 하셨는지 몰라 도움을 드리기 힘듭니다.

다만 위에 작성해주신 오류는, 두 개 이상의 `DaumPostcode` 를 동시에 랜더링 할 때 발생하는 것이 아닌가 합니다. `DaumPostcode` 는 다음 우편번호 스크립트를 동적으로 로드합니다. 그런데 두 개를 '동시에' 랜더링 하는 상황은 현재 고려하고 있지 않아서...

**Comment by Unknown123465** [comment]
오류 찾아냈습니다
DaumPostcode컴포넌트 랜더링 할 때 script태그가 뒤늦게 열어져서 Helmet으로 script태그를 먼저 불러온 다음에 DaumPostcode 랜더링했더니 잘되더라고요

답변 주셔서 감사합니다! 좋은 하루 되세요 :)

**Comment by Normaltic** [comment]
> 오류 찾아냈습니다 DaumPostcode컴포넌트 랜더링 할 때 script태그가 뒤늦게 열어져서 Helmet으로 script태그를 먼저 불러온 다음에 DaumPostcode 랜더링했더니 잘되더라고요

추후 해당 케이스에 대해서 개선해 보겠습니다. 감사합니다!
