### ISSUE TITLE
닫기 버튼 추가 방법 문의

### ISSUE THREAD

**Issue by hardline** [bernard-kms/react-daum-postcode#5]
우선 react 패키지 만들어 주셔서 감사합니다.

http://postcode.map.daum.net/guide 에 레이어 형태의 예제를 보면 레이어 우상단에 닫기 버튼이 존재합니다.

아래와 같은 형태의 img태그가 추가되어 닫기 버튼이 추가되는데 현재 react-daum-postcode에서 가능한 방법이 없는것으로 보입니다.

```
<div id="layer" style="display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;">
<img src="//t1.daumcdn.net/postcode/resource/images/close.png" id="btnCloseLayer" style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()" alt="닫기 버튼">
</div>
```
추가가 가능한 방법이 있을지 문의 드립니다.

**Comment by bernard-kms** [comment]
안녕하세요. 현재 react-daum-postcode는 가벼운 wrapper 라이브러리를 지향하고 있어서, 편의상의 기능을 특별히 지원하고 있지는 않습니다.

**Comment by hardline** [comment]
닫기 버튼 태그가 꼭 안쪽에 있을필요가 없었네요. 감사합니다 :)
