### ISSUE TITLE
React router dom과 같이 사용할 때 문제가 생깁니다..

### ISSUE THREAD

**Issue by SoheeP** [bernard-kms/react-daum-postcode#52]
React router dom은 6버전을 사용하고 있고, 라우터에 `/address` 링크를 클릭하면 아래 `Postcode` 컴포넌트를 랜더링하게 했는데요.
아래처럼 `complete`가 떨어졌을 때 홈으로 이동하게 했더니, router 에러가 발생하더라고요..
구체적인 에러메세지가 뜨기보단 라우터 모듈이랑 뭔가 충돌이 나서 발생한 것 같은데 어떤 상황인지 몰라서 일단 이슈에 남겨놓습니다.

아래 코드에서 `return <div><DaumPostcodeEmbed .... /></div>` 처럼 div로 한번 감싸면 에러가 안나더라고요 🤔..?

```jsx
export const Postcode = (props: any) => {
  const navigate = useNavigate();
  const handleComplete = (data: Address) => {
    let fullAddress = data.address;
    let extraAddress = '';

    if (data.addressType === 'R') {
      if (data.bname !== '') {
        extraAddress += data.bname;
      }
      if (data.buildingName !== '') {
        extraAddress +=
          extraAddress !== '' ? `, ${data.buildingName}` : data.buildingName;
      }
      fullAddress += extraAddress !== '' ? ` (${extraAddress})` : '';
    }

    console.log(fullAddress); // e.g. '서울 성동구 왕십리로2길 20 (성수동1가)'
  };

  const goHome = () => {
    navigate('/');
  };

  return (
      <DaumPostcodeEmbed
        onComplete={handleComplete}
        onClose={goHome}
        {...props}
      />
  );
};
```

**Comment by MaetDol** [comment]
같이 프로젝트 진행하다가 만난 문제에요.
typescript 템플릿으로 만드니 에러 메시지가 안나와서..
저도 재현해보려 typescript 가 아닌 CRA로 해보고 있는데, 이런 에러가 나와요

![image](https://user-images.githubusercontent.com/20384262/192077872-310b348e-b25f-4060-9fe6-d8b53b416f4c.png)

CRA로 만든 App.js 의 코드는 아래와 같아요
```jsx
import DaumPostcodeEmbed from 'react-daum-postcode';
import {
  BrowserRouter,
  Link,
  Route,
  Routes,
  useNavigate,
} from 'react-router-dom';

function App() {
  return (
    <BrowserRouter>
      <Link to="/address">주소 검색하기!</Link>
      <Routes>
        <Route path="/" element={<div>홈이에요!</div>} />
        <Route path="/address" element={<Postcode />} />
      </Routes>
    </BrowserRouter>
  );
}

function Postcode() {
  const navigate = useNavigate();
  const backToMain = () => {
    navigate('/');
  };
  return <DaumPostcodeEmbed onComplete={backToMain} onClose={backToMain} />;
}

export default App;
```

**Comment by MaetDol** [comment]
https://github.com/bernard-kms/react-daum-postcode/blob/02cdc93c5deee33e8c52d6aae38f5b0aa4d03ea7/src/DaumPostcodeEmbed.tsx#L66-L69

아! 확인해보니, 완료 했을 때 `this.wrap.current.remove()` 로 지워주고 있네요

<br>

https://github.com/bernard-kms/react-daum-postcode/blob/02cdc93c5deee33e8c52d6aae38f5b0aa4d03ea7/src/DaumPostcodeEmbed.tsx#L89-L93

그래서 요소가 지워진 상태에서, 라우팅 되어서 리액트가 Postcode 요소를 unmount 하려 하니, 
유일하게 렌더링하는 컴포넌트인 `DaumPostcodeEmbed` 는 이미 remove() 된 상태라 removeChild 할때 이런 에러가 나는 것 같아요

![image](https://user-images.githubusercontent.com/20384262/192079204-17e57c1b-f3a5-4552-b899-89704bed0486.png)

**Comment by MaetDol** [comment]
개인적인 의견으로는, DOM을 직접 관리하기보단 완료했을때 `완료 상태`를 업데이트 하고,
렌더링할때 `완료 상태`에 따라 그려주면 어떨까? 하는 생각이기도 해요 🤔🤔

혹시 더 좋거나 깔끔한 방법이 있을까요??

**Comment by Normaltic** [comment]
안녕하세요, 이슈 감사드립니다!

해당 문제는 https://github.com/bernard-kms/react-daum-postcode/issues/52#issuecomment-1256849948 에서 말씀하신대로, DOM 에 직접 접근하여 지우는 것이 원인으로 판단됩니다. 단, `react-router` 와의 충돌은 아닌 것으로 보여요. React 에서 컴포넌트가 없어질 때 내부 로직을 통해 돔에서 제거할텐데, 직접 제거(`element.remove`)하면 React 는 없어진지 알지 못할거고, 그로 인해 벌어진 일이 아닐까 싶습니다. 아래와 같은 로직에서 동일한 증상 구현이 가능하네요.

```ts
import { useEffect, useRef, useState } from "react";

export const Test = () => {
  const ref = useRef<HTMLDivElement>(null);
  const [isShow, setShow] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      ref.current?.remove();

      setTimeout(() => {
        setShow(false);
      }, 1000)

    }, 1000)
  }, [])

  if( isShow === false ) return null;

  return (
    <div ref={ref}>asd</div>
  );
};
```

div 태그로 한 번 감싸면 괜찮은 이유는, React 가 컴포넌트를 돔에서 제거할 때 해당 컴포넌트의 루트 엘리먼트를 가지고 처리하기 때문이 아닌가 생각됩니다.

현재 올려주신 로직에서는, `autoClose` props 를 false 로 전달하고, `navigate('/')` 를 `onComplete` 콜백에서 처리하면 회피가 가능할 것으로 보입니다. 그리고 의견 주신 대로 엘리먼트를 직접 제거 하기보단, 플래그를 통한 동적 랜더링으로 처리하는게 나아 보입니다!

**Comment by MaetDol** [comment]
네!! 말씀해주신 `autoClose=false`와 `div`  래핑을 통해 사용할게요

답변 감사합니다!!

**Comment by SoheeP** [comment]
답변 주셔서 감사합니다!
