### ISSUE TITLE
react-daum-postcode 사용 시 theme 설정 가능여부 문의드립니다.

### ISSUE THREAD

**Issue by joyfive** [bernard-kms/react-daum-postcode#55]
Daum postcode 다음 공식 우편번호 서비스에서 제공하는 '테마' 설정을 하고 싶은데요. 
react-daum-postcode 라이브러리를 활용해서 우편번호 서비스 api에 접근하고 있어서 react-daum-postcode 라이브러리에서도 테마(컬러) 설정이 가능할지 문의드립니다.

https://postcode.map.daum.net/guide#themeWizard

공식 문서에서 제공하는 가이드로는, 지정된 변수명으로 원하는 컬러 hexcode를 themeObj 객체로 전달하고 있습니다. react-daum-postcode에서도 themeObj를 포함하여 전달하는 방식이 가능할까요?

[첨부: 공식문서 내 테마설정 가이드]

```//아래 코드처럼 테마 객체를 생성합니다.(color값은 #F00, #FF0000 형식으로 입력하세요.)
//변경되지 않는 색상의 경우 주석 또는 제거하시거나 값을 공백으로 하시면 됩니다.
var themeObj = {
   //bgColor: "", //바탕 배경색
   //searchBgColor: "", //검색창 배경색
   //contentBgColor: "", //본문 배경색(검색결과,결과없음,첫화면,검색서제스트)
   //pageBgColor: "", //페이지 배경색
   //textColor: "", //기본 글자색
   //queryTextColor: "", //검색창 글자색
   //postcodeTextColor: "", //우편번호 글자색
   //emphTextColor: "", //강조 글자색
   //outlineColor: "" //테두리
};

//위에서 생성한 themeObj객체를 우편번호 서비스 생성자에 넣습니다.
//생성자의 자세한 설정은 예제 및 속성탭을 확인해 주세요.
/*
new daum.Postcode({
   theme: themeObj
}).open();

new daum.Postcode({
   theme: themeObj
}).embed(target);
*/```

**Comment by Normaltic** [comment]
안녕하세요!

`react-daum-postcode` 는 다음 우편번호 서비스를 리액트에서 쉽게 쓸 수 있도록 하는 Wrapper 역할로써, 다음 우편번호 서비스의 명세를 그대로 따라가고 있습니다. 따라서 테마 역시 우편번호 서비스에 작성된 명세 대로 사용할 수 있습니다.

**Comment by joyfive** [comment]
아! 확인 감사합니다!! 
변수명 전달하는데 어려움을 겪어서 문의를 남겼었는데, 된다는 확신을 주셔서 재도전하는 도중에 성공했습니다ㅎㅎㅎㅎ 감사합니다!!
