### ISSUE TITLE
submitMode 은 type 이 정의되지 않은 이유가 있을까요?

### ISSUE THREAD

**Issue by LeeJiJong** [bernard-kms/react-daum-postcode#6]
submitMode를 props로 받아서 써야하는데 type 에러가 나던데
type이 정의되지 않은 것 같은데 따로 이유가 있나요?

**Comment by bernard-kms** [comment]
@LeeJiJong 안녕하세요! 이슈를 제보해주셔서 감사합니다. `submitMode`가 실수로 타입정의에서 누락되었던 것 같습니다. https://github.com/bernard-kms/react-daum-postcode/commit/fea2b45abea4c5b01d0d3585d409879b98c9cc08 에서 해당 문제를 해결하여 `1.8.4` 버전으로 배포했습니다.

**Comment by LeeJiJong** [comment]
네 빠른 수정 감사합니다.
